Fix nil error in ActionController::Probe
The line changed can throw `NoMethodError·undefined method 'empty?' for nil:NilClass` if content_type is nil

```
nil.respond_to?(:to_s)  # => true
nil.to_s.split(';').first    # => nil
nil.empty?    # => raises NoMethodError
```